server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/bankdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: event-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
